export default function AI_Search1(props) {
    return (
        <Backdrop_content header="AI Answer" description={<p>Generated by ChatGPT. Answers may be incorect.</p>}>
            <div className="typewriter column row_gap_4">
                <p>In the U.S., fall (autumn) 2025 begins on Monday, September 22, 2025, and ends on Sunday, December 21, 2025, based on the astronomical seasons.

However, meteorological fall (used for weather and climate purposes) runs from September 1 to November 30 each year.</p>
                <div className="row column_gap_4">
                    <input className="width_100" placeholder="Start typing..." />
                    <Button_with_icon icon="/icons/file-regular.svg"/>
                    <Button_with_icon style={{ padding: 4 }} icon_style={{ width: 28, height: 28 }} icon="/icons/send-outline.svg"/>
                </div>
            </div>
        </Backdrop_content>
    )
}