[default.databases.rusqlite]
url = "file:rusqlite?mode=memory&cache=shared"

[default.databases.sqlx]
url = "db/sqlx/db.sqlite"

[default.databases.diesel]
url = "db/diesel/db.sqlite"
timeout = 10

[global]
address = "0.0.0.0"
port = 4459

[development]
address = "0.0.0.0"
port = 4459